name: Alpha release & deploy

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: ignt

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run alpha
        env:
          NODE_AUTH_TOKEN: ${{secrets.sp_npm_token}}

      - name: Install Spellshape CLI
        run: 'curl https://get.spellshape.com/cli! | bash'

      - name: Install alpha
        run: lerna exec --scope='@spellshape/template' -- npm i @spellshape/vue@alpha @spellshape/vuex@alpha

      - name: Build
        run: npm run build

      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --alias 'alpha'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
